version: '3.9'
services:
  nginx_container:
    image: nginx
    ports:
    - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - public
      - app

  backend:
    image: piotrszymanski/test-error-logs-app:1.0
    expose:
      - "80"
    volumes:
      - C:\Program Files\EaseUS\EaseUS Data Recovery Wizard:/home
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    networks:
      - app

  app_db:
    image: mysql:8.0.1
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: password
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 10s
      resources:
        limits:
          memory: 1024M
    networks:
      - app

  usage_rabbit:
    image: rabbitmq:3.10
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 10s
    networks:
      - usage
      - app

  usage_consumer:
    image: piotrszymanski/test-app:1.0
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 10s
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  usage_db:
    image: mysql:8.0.1
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - usage_db_volume:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 10s
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
    networks:
      - usage

volumes:
  usage_db_volume:
  app_db_volume:

networks:
  app:
  public:
  usage:
